name: Tests
on: push
jobs:

  tests:
    name: Tests
    runs-on: ubuntu-latest
    container: python:3.9

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: install cookiecutter
        run: pip install cookiecutter
      - name: checkout
        uses: actions/checkout@v2
      - name: run tests
        run: |
          cd ${{ github.workspace }}
          ./scripts/test
        env:
          TEST_DB_CONNECTION: postgres://postgres:postgres@localhost/postgres
